function responseDetails = doPhase(tm, ...
    phase, ...
    stimSpec, ...
    inputOptions, ...
    framesPerUpdate, ...
    displayText, ...
    allowScreenLabel, ...
    station, ...
    window, ...
    ifi, ...
    manualOn, ...
    timingCheckPct, ...
    numFrameDropReports)

'waitForRequest'
'presentDiscriminandum'
'performReinforcement'
'performReinforcement'

