function d=display(s)

    disp(struct(s))
    disp(struct(s.stimManager))
    d='sucka!';
%     d=['orientedGabors (n target, m distractor gabors, randomized phase, equal spatial frequency, p>=n+m horiz positions)\n'...
%         '\t\t\tpixPerCycs:\t[' num2str(s.pixPerCycs) ... 
%         ']\n\t\t\ttarget orientations:\t[' num2str(s.targetOrientations) ...
%         ']\n\t\t\tdistractor orientations:\t[' num2str(s.distractorOrientations) ...
%         ']\n\t\t\tmean:\t' num2str(s.mean) ...
%         '\n\t\t\tradius:\t' num2str(s.radius) ...
%         '\n\t\t\tcontrast:\t' num2str(s.contrast) ...
%         '\n\t\t\tthresh:\t' num2str(s.thresh) ...
%         '\n\t\t\tpct from top:\t' num2str(s.yPosPct)];
%     d=sprintf(d);