function d=display(s)
    type='';
    switch s.flickerType
        case 0
            type = 'binary flicker';
        case 1
            type = 'Gaussian flicker';
        otherwise
            error('Invalid hemifield flicker type in display()')
    end
    d=['hemifieldFlicker (n target, m distractor fields, ' type ' type)\n'...
        '\t\t\tpixPerCycs:\t[' num2str(s.pixPerCycs) ... 
        ']\n\t\t\ttarget contrasts:\t[' num2str(s.targetContrasts) ...
        ']\n\t\t\tdistractor contrasts:\t[' num2str(s.distractorContrasts) ...
        ']\n\t\t\tfieldWidthPct:\t' num2str(s.fieldWidthPct) ...
        ']\n\t\t\tfieldHeightPct:\t' num2str(s.fieldHeightPct) ...
        ']\n\t\t\tmean:\t' num2str(s.mean) ...
        '\n\t\t\tstddev:\t' num2str(s.stddev) ...
        '\n\t\t\tthresh:\t' num2str(s.thresh) ...
        '\n\t\t\tpct from top:\t' num2str(s.yPosPct)];
    d=sprintf(d);