function [h,r]=getRatrixHeatInfo(rack)

assignments={...
    %subjectID  %rack   %position       %heat   %owner  %experiment 
    {'179'      2       'A'           'red'   'aj/hv'    'tube xfer'},...
    {'180'      2       'B'           'red'   'aj/hv'    'tube xfer'},...
    {'165'      2       'C'           'red'   'aj/hv'    'flicker'},...
    {'178'      2       'D'           'red'   'aj/hv'    'box xfer'},...
    {'177'      2       'E'           'red'   'aj/hv'    'box xfer'},...
    {'166'      2       'F'           'red'   'aj/hv'    'flicker'},...
    ...%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    {'159'      2       'A'           'orange'   'aj/hv'    'tube phys'},...
    {'160'      2       'B'           'orange'   'aj/hv'    'tube phys'},...
    {'173'      2       'C'           'orange'   'dp'    'x modal'},...
    {'174'      2       'D'           'orange'   'dp'    'x modal'},...
    {'175'      2       'E'           'orange'   'dp'    'x modal'},...
    {'176'      2       'F'           'orange'   'dp'    'x modal'},...
    ...%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    {'185'      2       'A'           'yellow'   'aj/hv'    'tube xfer'},...
    {'186'      2       'B'           'yellow'   'aj/hv'    'tube xfer'},...
    {'167'      2       'C'           'yellow'   'aj/hv'    'flicker'},...
    {'184'      2       'D'           'yellow'   'aj/hv'    'box xfer'},...
    {'183'      2       'E'           'yellow'   'aj/hv'    'box xfer'},...
    {'168'      2       'F'           'yellow'   'aj/hv'    'flicker'},...
    ...%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    {'161'      2       'A'           'green'   'aj/hv'    'tube phys'},...
    {'162'      2       'B'          'green'   'aj/hv'    'tube phys'},...
    {'181'      2       'C'           'green'   'edf'    'rel cue'},...
    {'182'      2       'D'           'green'   'edf'    'rel cue'},...
    {'187'      2       'E'           'green'   'edf'    'rel cue'},...
    {'188'      2       'F'           'green'   'edf'    'rel cue'},...
    ...%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    {'163'      2       'A'           'blue'   'aj/hv'    'tube phys'},...
    {'164'      2       'B'           'blue'   'aj/hv'    'tube phys'},...
    {'189'      2       'C'           'blue'   'edf'    'rel blk'},...
    {'190'      2       'D'           'blue'   'edf'    'rel blk'},...
    {'191'      2       'E'           'blue'   'edf'    'rel blk'},...
    {'192'      2       'F'           'blue'   'edf'    'rel blk'}...
    ...%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    {'test1'      2       'A'           'test'   'test'    'free drinks'},...
    {'test2'      2       'B'           'test'   'test'    'free drinks'},...
    {'test3'      2       'C'           'test'   'test'    'free drinks'},...
    {'test4'      2       'D'           'test'   'test'    'free drinks'},...
    {'test5'      2       'E'           'test'   'test'    'free drinks'},...
    {'test6'      2       'F'           'test'   'test'    'free drinks'},...
    ...%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    {'test1'      3       'A'           'test'   'test'    'free drinks'},...
    {'test2'      3       'B'           'test'   'test'    'free drinks'},...
    {'test3'      3       'C'           'test'   'test'    'free drinks'},...
    {'test4'      3       'D'           'test'   'test'    'free drinks'},...
    {'test5'      3       'E'           'test'   'test'    'free drinks'},...
    {'test6'      3       'F'           'test'   'test'    'free drinks'},...
    {'test7'      3       'G'           'test'   'test'    'free drinks'},...
    {'test8'      3       'H'           'test'   'test'    'free drinks'},...
    {'test9'      3       'I'           'test'   'test'    'free drinks'},...
    };

heats={...
    {'red',     [1 0 0]},...
    {'orange',  [1 .5 0]},...
    {'yellow',  [1 1 0]},...
    {'green',   [0 1 0]},...
    {'blue',    [0 0 1]},...
    {'test',    [0 0 0]}};


r=getRatrixRackInfo(rack);
stations=getRatrixStationInfo([]);

for i=1:length(heats)
    h{i,1}=heats{i};
    h{i,2}={};
    n=0;
    for j=1:length(assignments)
        if assignments{j}{2}==rack && strcmp(assignments{j}{4},h{i,1}{1})
            s={assignments{j}{1} getRatrixStationInfo({rack assignments{j}{3}}) assignments{j}{5:6}};
            if check(r,h{i,2},s{2}{1},assignments{j}{1})%position exists and not filled for that heat
                %note i fail to check if the subject is signed up for another *rack* on the same heat
                h{i,2}{n+1}=s;
                n=n+1;
            else
                error('check failed')
            end
        end
    end

end

function out=check(rackSize,heatMembers,proposedLoc,name)

out=ismember(proposedLoc(1),1:rackSize(1)) && ismember(proposedLoc(2),1:rackSize(2));
if ~out
    error('propsed location doesn''t exist in that rack')
end
for i=1:length(heatMembers)
    if strcmp(name,heatMembers{i}{1}) || all(proposedLoc==heatMembers{i}{2}{1})
        out=false;
        error('multiple entries for same subject or location in a heat')
    end    
end