function sm=makeStandardSoundManager()
% this is the sound manager that most rlab user have
% some users may define their own custom sounds.
% do not change the function (from the rat's point of view)


sm=soundManager({soundClip('correctSound','allOctaves',[400],20000), ...
            soundClip('keepGoingSound','allOctaves',[300],20000), ...
            soundClip('trySomethingElseSound','gaussianWhiteNoise'), ...
            soundClip('wrongSound','tritones',[300 400],20000),... 
            soundClip('trialStartSound','empty')});
        
