function createfigure(cdata1, cdata2, cdata3, cdata4, cdata5, cdata6, cdata7, cdata8, cdata9, cdata10, cdata11, cdata12, cdata13, cdata14, cdata15, cdata16, cdata17, cdata18, cdata19, cdata20, cdata21, cdata22, cdata23, cdata24, cdata25, cdata26, cdata27, cdata28)
%CREATEFIGURE(CDATA1, CDATA2, CDATA3, CDATA4, CDATA5, CDATA6, CDATA7, CDATA8, CDATA9, CDATA10, CDATA11, CDATA12, CDATA13, CDATA14, CDATA15, CDATA16, CDATA17, CDATA18, CDATA19, CDATA20, CDATA21, CDATA22, CDATA23, CDATA24, CDATA25, CDATA26, CDATA27, CDATA28)
%  CDATA1:  image cdata
%  CDATA2:  image cdata
%  CDATA3:  image cdata
%  CDATA4:  image cdata
%  CDATA5:  image cdata
%  CDATA6:  image cdata
%  CDATA7:  image cdata
%  CDATA8:  image cdata
%  CDATA9:  image cdata
%  CDATA10:  image cdata
%  CDATA11:  image cdata
%  CDATA12:  image cdata
%  CDATA13:  image cdata
%  CDATA14:  image cdata
%  CDATA15:  image cdata
%  CDATA16:  image cdata
%  CDATA17:  image cdata
%  CDATA18:  image cdata
%  CDATA19:  image cdata
%  CDATA20:  image cdata
%  CDATA21:  image cdata
%  CDATA22:  image cdata
%  CDATA23:  image cdata
%  CDATA24:  image cdata
%  CDATA25:  image cdata
%  CDATA26:  image cdata
%  CDATA27:  image cdata
%  CDATA28:  image cdata

%  Auto-generated by MATLAB on 23-Apr-2021 13:22:53

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'Position',[0 1 1 1],'Tag','suptitle');
axis off

% Create text
text('Parent',axes1,'HorizontalAlignment','center','FontSize',14,...
    'String','peri-stimulus cortical response to varying contrasts',...
    'Position',[0.5 -0.05 0],...
    'Visible','on');

% Create subplot
subplot1 = subplot(7,4,1,'Parent',figure1);
axis off
hold(subplot1,'on');

% Create image
image(cdata1,'Parent',subplot1,'CDataMapping','scaled');

box(subplot1,'on');
axis(subplot1,'tight');
axis(subplot1,'ij');
% Set the remaining axes properties
set(subplot1,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot2 = subplot(7,4,2,'Parent',figure1);
axis off
hold(subplot2,'on');

% Create image
image(cdata2,'Parent',subplot2,'CDataMapping','scaled');

box(subplot2,'on');
axis(subplot2,'tight');
axis(subplot2,'ij');
% Set the remaining axes properties
set(subplot2,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot3 = subplot(7,4,3,'Parent',figure1);
axis off
hold(subplot3,'on');

% Create image
image(cdata3,'Parent',subplot3,'CDataMapping','scaled');

box(subplot3,'on');
axis(subplot3,'tight');
axis(subplot3,'ij');
% Set the remaining axes properties
set(subplot3,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot4 = subplot(7,4,4,'Parent',figure1);
axis off
hold(subplot4,'on');

% Create image
image(cdata4,'Parent',subplot4,'CDataMapping','scaled');

box(subplot4,'on');
axis(subplot4,'tight');
axis(subplot4,'ij');
% Set the remaining axes properties
set(subplot4,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot5 = subplot(7,4,5,'Parent',figure1);
axis off
hold(subplot5,'on');

% Create image
image(cdata5,'Parent',subplot5,'CDataMapping','scaled');

box(subplot5,'on');
axis(subplot5,'tight');
axis(subplot5,'ij');
% Set the remaining axes properties
set(subplot5,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot6 = subplot(7,4,6,'Parent',figure1);
axis off
hold(subplot6,'on');

% Create image
image(cdata6,'Parent',subplot6,'CDataMapping','scaled');

box(subplot6,'on');
axis(subplot6,'tight');
axis(subplot6,'ij');
% Set the remaining axes properties
set(subplot6,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot7 = subplot(7,4,7,'Parent',figure1);
axis off
hold(subplot7,'on');

% Create image
image(cdata7,'Parent',subplot7,'CDataMapping','scaled');

box(subplot7,'on');
axis(subplot7,'tight');
axis(subplot7,'ij');
% Set the remaining axes properties
set(subplot7,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot8 = subplot(7,4,8,'Parent',figure1);
axis off
hold(subplot8,'on');

% Create image
image(cdata8,'Parent',subplot8,'CDataMapping','scaled');

box(subplot8,'on');
axis(subplot8,'tight');
axis(subplot8,'ij');
% Set the remaining axes properties
set(subplot8,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot9 = subplot(7,4,9,'Parent',figure1);
axis off
hold(subplot9,'on');

% Create image
image(cdata9,'Parent',subplot9,'CDataMapping','scaled');

box(subplot9,'on');
axis(subplot9,'tight');
axis(subplot9,'ij');
% Set the remaining axes properties
set(subplot9,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot10 = subplot(7,4,10,'Parent',figure1);
axis off
hold(subplot10,'on');

% Create image
image(cdata10,'Parent',subplot10,'CDataMapping','scaled');

box(subplot10,'on');
axis(subplot10,'tight');
axis(subplot10,'ij');
% Set the remaining axes properties
set(subplot10,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot11 = subplot(7,4,11,'Parent',figure1);
axis off
hold(subplot11,'on');

% Create image
image(cdata11,'Parent',subplot11,'CDataMapping','scaled');

box(subplot11,'on');
axis(subplot11,'tight');
axis(subplot11,'ij');
% Set the remaining axes properties
set(subplot11,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot12 = subplot(7,4,12,'Parent',figure1);
axis off
hold(subplot12,'on');

% Create image
image(cdata12,'Parent',subplot12,'CDataMapping','scaled');

box(subplot12,'on');
axis(subplot12,'tight');
axis(subplot12,'ij');
% Set the remaining axes properties
set(subplot12,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot13 = subplot(7,4,13,'Parent',figure1);
axis off
hold(subplot13,'on');

% Create image
image(cdata13,'Parent',subplot13,'CDataMapping','scaled');

box(subplot13,'on');
axis(subplot13,'tight');
axis(subplot13,'ij');
% Set the remaining axes properties
set(subplot13,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot14 = subplot(7,4,14,'Parent',figure1);
axis off
hold(subplot14,'on');

% Create image
image(cdata14,'Parent',subplot14,'CDataMapping','scaled');

box(subplot14,'on');
axis(subplot14,'tight');
axis(subplot14,'ij');
% Set the remaining axes properties
set(subplot14,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot15 = subplot(7,4,15,'Parent',figure1);
axis off
hold(subplot15,'on');

% Create image
image(cdata15,'Parent',subplot15,'CDataMapping','scaled');

box(subplot15,'on');
axis(subplot15,'tight');
axis(subplot15,'ij');
% Set the remaining axes properties
set(subplot15,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot16 = subplot(7,4,16,'Parent',figure1);
axis off
hold(subplot16,'on');

% Create image
image(cdata16,'Parent',subplot16,'CDataMapping','scaled');

box(subplot16,'on');
axis(subplot16,'tight');
axis(subplot16,'ij');
% Set the remaining axes properties
set(subplot16,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot17 = subplot(7,4,17,'Parent',figure1);
axis off
hold(subplot17,'on');

% Create image
image(cdata17,'Parent',subplot17,'CDataMapping','scaled');

box(subplot17,'on');
axis(subplot17,'tight');
axis(subplot17,'ij');
% Set the remaining axes properties
set(subplot17,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot18 = subplot(7,4,18,'Parent',figure1);
axis off
hold(subplot18,'on');

% Create image
image(cdata18,'Parent',subplot18,'CDataMapping','scaled');

box(subplot18,'on');
axis(subplot18,'tight');
axis(subplot18,'ij');
% Set the remaining axes properties
set(subplot18,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot19 = subplot(7,4,19,'Parent',figure1);
axis off
hold(subplot19,'on');

% Create image
image(cdata19,'Parent',subplot19,'CDataMapping','scaled');

box(subplot19,'on');
axis(subplot19,'tight');
axis(subplot19,'ij');
% Set the remaining axes properties
set(subplot19,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot20 = subplot(7,4,20,'Parent',figure1);
axis off
hold(subplot20,'on');

% Create image
image(cdata20,'Parent',subplot20,'CDataMapping','scaled');

box(subplot20,'on');
axis(subplot20,'tight');
axis(subplot20,'ij');
% Set the remaining axes properties
set(subplot20,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot21 = subplot(7,4,21,'Parent',figure1);
axis off
hold(subplot21,'on');

% Create image
image(cdata21,'Parent',subplot21,'CDataMapping','scaled');

box(subplot21,'on');
axis(subplot21,'tight');
axis(subplot21,'ij');
% Set the remaining axes properties
set(subplot21,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot22 = subplot(7,4,22,'Parent',figure1);
axis off
hold(subplot22,'on');

% Create image
image(cdata22,'Parent',subplot22,'CDataMapping','scaled');

box(subplot22,'on');
axis(subplot22,'tight');
axis(subplot22,'ij');
% Set the remaining axes properties
set(subplot22,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot23 = subplot(7,4,23,'Parent',figure1);
axis off
hold(subplot23,'on');

% Create image
image(cdata23,'Parent',subplot23,'CDataMapping','scaled');

box(subplot23,'on');
axis(subplot23,'tight');
axis(subplot23,'ij');
% Set the remaining axes properties
set(subplot23,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot24 = subplot(7,4,24,'Parent',figure1);
axis off
hold(subplot24,'on');

% Create image
image(cdata24,'Parent',subplot24,'CDataMapping','scaled');

box(subplot24,'on');
axis(subplot24,'tight');
axis(subplot24,'ij');
% Set the remaining axes properties
set(subplot24,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot25 = subplot(7,4,25,'Parent',figure1);
axis off
hold(subplot25,'on');

% Create image
image(cdata25,'Parent',subplot25,'CDataMapping','scaled');

box(subplot25,'on');
axis(subplot25,'tight');
axis(subplot25,'ij');
% Set the remaining axes properties
set(subplot25,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot26 = subplot(7,4,26,'Parent',figure1);
axis off
hold(subplot26,'on');

% Create image
image(cdata26,'Parent',subplot26,'CDataMapping','scaled');

box(subplot26,'on');
axis(subplot26,'tight');
axis(subplot26,'ij');
% Set the remaining axes properties
set(subplot26,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot27 = subplot(7,4,27,'Parent',figure1);
axis off
hold(subplot27,'on');

% Create image
image(cdata27,'Parent',subplot27,'CDataMapping','scaled');

box(subplot27,'on');
axis(subplot27,'tight');
axis(subplot27,'ij');
% Set the remaining axes properties
set(subplot27,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
% Create subplot
subplot28 = subplot(7,4,28,'Parent',figure1);
axis off
hold(subplot28,'on');

% Create image
image(cdata28,'Parent',subplot28,'CDataMapping','scaled');

box(subplot28,'on');
axis(subplot28,'tight');
axis(subplot28,'ij');
% Set the remaining axes properties
set(subplot28,'CLim',[0 0.1],'DataAspectRatio',[1 1 1],'Layer','top');
