function d=display(r)
    d=[sprintf('\n\t\t\trewardSizeULorMS:\t\t%3.3g',r.rewardSizeULorMS) ...
       sprintf('\n\t\t\tmsPenalty:\t\t\t\t%d',r.msPenalty) ...
       sprintf('\n\t\t\tscalar:\t\t\t\t\t%3.3g',r.scalar) ...
       ];
   
   %add on the superclass 
    d=[d sprintf('\n\t\treinforcementManager:\t') display(r.reinforcementManager)];