run('C:\Documents and Settings\rlab\Desktop\ratrix\analysis\analysisScripts\sampleAnalysisParameters')
subjectID = '305';
%% Rat Number 305
%cellBoundary={'trialRange',[1 2]} % orGr: 8 orientations.  waveform: sine.
%cellBoundary={'trialRange',[3 7]} % tempGr: 4 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[8 13]} % spatGr: 9 spatFreqs.  waveform: sine.
%cellBoundary={'trialRange',[14 15]} % orGr: 16 orientations.  waveform: square.
%cellBoundary={'trialRange',[16 22]} % ffgwn
%cellBoundary={'trialRange',[23 25]} % orGr: 8 orientations.  waveform: sine.
%cellBoundary={'trialRange',[26 27]} % ffbinwn
%cellBoundary={'trialRange',[28 29]} % 6X8 binary checkerboard
% cellBoundary={'trialRange',[30 40]} % h-bars
% cellBoundary={'trialRange',[41 52]} % v-bars
%cellBoundary={'trialRange',[53]} % tempGr: 4 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[54 55]} % ffgwn
%cellBoundary={'trialRange',[56 66]} % spatGr: 9 spatFreqs.  waveform: sine.
%cellBoundary={'trialRange',[67 81]} % h-bars
%cellBoundary={'trialRange',[82 96]} % v-bars
%cellBoundary={'trialRange',[97 99]} % spatGr: 9 spatFreqs.  waveform: sine.
%cellBoundary={'trialRange',[100 101]} % orGr: 8 orientations.  waveform: sine.
%cellBoundary={'trialRange',[102 104]} % spatGr: 9 spatFreqs.  waveform: sine.
%cellBoundary={'trialRange',[105 108]} % tempGr: 4 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[109]} % tempGr: 4 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[110]} % ffgwn
%cellBoundary={'trialRange',[111]} % orGr: 8 orientations.  waveform: sine.
%cellBoundary={'trialRange',[112]} % spatGr: 9 spatFreqs.  waveform: sine.
%cellBoundary={'trialRange',[113 115]} % tempGr: 4 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[116]} % orGr: 8 orientations.  waveform: sine.
%cellBoundary={'trialRange',[117 119]} % tempGr: 4 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[120 121]} % spatGr: 9 spatFreqs.  waveform: sine.
%cellBoundary={'trialRange',[122 123]} % orGr: 8 orientations.  waveform: sine.
%cellBoundary={'trialRange',[124 127]} % ffgwn
%cellBoundary={'trialRange',[128]} % orGr: 8 orientations.  waveform: sine.
%cellBoundary={'trialRange',[129 133]} % tempGr: 4 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[134]} % orGr: 8 orientations.  waveform: sine.
%cellBoundary={'trialRange',[135 137]} % tempGr: 4 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[138 140]} % spatGr: 9 spatFreqs.  waveform: sine.
%cellBoundary={'trialRange',[141 142]} % tempGr: 2 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[143]} % tempGr: 4 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[144]} % spatGr: 9 spatFreqs.  waveform: sine.
%cellBoundary={'trialRange',[145]} % orGr: 8 orientations.  waveform: sine.
%cellBoundary={'trialRange',[146]} % orGr: 16 orientations.  waveform: square.
%cellBoundary={'trialRange',[147 149]} % tempGr: 2 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[150]} % tempGr: 4 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[151]} % spatGr: 9 spatFreqs.  waveform: sine.
%cellBoundary={'trialRange',[152]} % orGr: 8 orientations.  waveform: sine.
%cellBoundary={'trialRange',[153]} % orGr: 16 orientations.  waveform: square.
%cellBoundary={'trialRange',[154]} % orGr: 8 orientations.  waveform: sine.
%cellBoundary={'trialRange',[155 158]} % tempGr: 2 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[159]} % tempGr: 4 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[160]} % spatGr: 9 spatFreqs.  waveform: sine.
%cellBoundary={'trialRange',[161]} % orGr: 8 orientations.  waveform: sine.
%cellBoundary={'trialRange',[162]} % orGr: 16 orientations.  waveform: square.
%cellBoundary={'trialRange',[163]} % ffgwn
%cellBoundary={'trialRange',[164 169]} % tempGr: 2 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[170 175]} % spatGr: 9 spatFreqs.  waveform: sine.
%cellBoundary={'trialRange',[176 180]} % tempGr: 2 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[181]} % tempGr: 4 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[182]} % spatGr: 9 spatFreqs.  waveform: sine.
%cellBoundary={'trialRange',[183]} % orGr: 8 orientations.  waveform: sine.
%cellBoundary={'trialRange',[184]} % orGr: 16 orientations.  waveform: square.
%cellBoundary={'trialRange',[185]} % ffgwn
%cellBoundary={'trialRange',[186 190]} % tempGr: 2 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[191]} % tempGr: 4 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[192]} % spatGr: 9 spatFreqs.  waveform: sine.
%cellBoundary={'trialRange',[193]} % orGr: 8 orientations.  waveform: sine.
%cellBoundary={'trialRange',[194]} % orGr: 16 orientations.  waveform: square.
%cellBoundary={'trialRange',[195]} % ffgwn
%cellBoundary={'trialRange',[196]} % tempGr: 2 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[197]} % tempGr: 4 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[198]} % spatGr: 9 spatFreqs.  waveform: sine.
%cellBoundary={'trialRange',[199]} % orGr: 16 orientations.  waveform: square.
%cellBoundary={'trialRange',[200 202]} % ffgwn
%cellBoundary={'trialRange',[203]} % tempGr: 2 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[204]} % tempGr: 4 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[205]} % spatGr: 9 spatFreqs.  waveform: sine.
%cellBoundary={'trialRange',[206]} % orGr: 8 orientations.  waveform: sine.
%cellBoundary={'trialRange',[207]} % orGr: 16 orientations.  waveform: square.
%cellBoundary={'trialRange',[208 211]} % ffgwn
%cellBoundary={'trialRange',[212 224]} % 6X8 binary checkerboard
%cellBoundary={'trialRange',[225]} % tempGr: 2 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[226 238]} % 6X8 binary checkerboard
%cellBoundary={'trialRange',[239 241]} % tempGr: 2 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[242 308]} % 24X32 binary checkerboard
%cellBoundary={'trialRange',[309 318]} % ffgwn
%cellBoundary={'trialRange',[319]} % 6X8 binary checkerboard
%cellBoundary={'trialRange',[320 333]} % 12X16 binary checkerboard
%cellBoundary={'trialRange',[334 337]} % 24X32 binary checkerboard
%cellBoundary={'trialRange',[338 340]} % tempGr: 2 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[341]} % ffgwn
%cellBoundary={'trialRange',[342 350]} % 6X8 binary checkerboard
%cellBoundary={'trialRange',[351]} % 12X16 binary checkerboard
%cellBoundary={'trialRange',[352 371]} % 24X32 binary checkerboard
%cellBoundary={'trialRange',[372]} % tempGr: 2 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[373]} % ffgwn
%cellBoundary={'trialRange',[374]} % 6X8 binary checkerboard
%cellBoundary={'trialRange',[375]} % 12X16 binary checkerboard
%cellBoundary={'trialRange',[376]} % tempGr: 2 tempFreqs.  waveform: sine.
%cellBoundary={'trialRange',[377]} % ffgwn
analysisManagerByChunk(subjectID, path, cellBoundary, spikeDetectionParams, ... 
 spikeSortingParams,timeRangePerTrialSecs,stimClassToAnalyze,overwriteAll,usePhotoDiodeSpikes,plottingParams)