run('C:\Documents and Settings\rlab\Desktop\ratrix\analysis\analysisScripts\sampleAnalysisParameters')
subjectID = '305';
%% Rat Number 305
%cellBoundary={'trialRange',[1 2]} % gratings
%cellBoundary={'trialRange',[3 7]} % gratings
%cellBoundary={'trialRange',[8 13]} % gratings
%cellBoundary={'trialRange',[14 15]} % gratings
%cellBoundary={'trialRange',[16 22]} % whiteNoise
%cellBoundary={'trialRange',[23 25]} % gratings
%cellBoundary={'trialRange',[26 27]} % whiteNoise
%cellBoundary={'trialRange',[28 29]} % whiteNoise
%cellBoundary={'trialRange',[30 40]} % whiteNoise
%cellBoundary={'trialRange',[41 52]} % whiteNoise
cellBoundary={'trialRange',[53]} % gratings
%cellBoundary={'trialRange',[54 55]} % whiteNoise
cellBoundary={'trialRange',[56 66]} % gratings
%cellBoundary={'trialRange',[67 81]} % whiteNoise
%cellBoundary={'trialRange',[82 96]} % whiteNoise
%cellBoundary={'trialRange',[97 99]} % gratings
%cellBoundary={'trialRange',[100 101]} % gratings
%cellBoundary={'trialRange',[102 104]} % gratings
%cellBoundary={'trialRange',[105 108]} % gratings
%cellBoundary={'trialRange',[109]} % gratings
%cellBoundary={'trialRange',[110]} % whiteNoise
%cellBoundary={'trialRange',[111]} % gratings
%cellBoundary={'trialRange',[112]} % gratings
%cellBoundary={'trialRange',[113 115]} % gratings
%cellBoundary={'trialRange',[116]} % gratings
%cellBoundary={'trialRange',[117 119]} % gratings
%cellBoundary={'trialRange',[120 121]} % gratings
%cellBoundary={'trialRange',[122 123]} % gratings
%cellBoundary={'trialRange',[124 127]} % whiteNoise
%cellBoundary={'trialRange',[128]} % gratings
%cellBoundary={'trialRange',[129 133]} % gratings
%cellBoundary={'trialRange',[134]} % gratings
%cellBoundary={'trialRange',[135 137]} % gratings
%cellBoundary={'trialRange',[138 140]} % gratings
%cellBoundary={'trialRange',[141 142]} % gratings
%cellBoundary={'trialRange',[143]} % gratings
%cellBoundary={'trialRange',[144]} % gratings
%cellBoundary={'trialRange',[145]} % gratings
%cellBoundary={'trialRange',[146]} % gratings
%cellBoundary={'trialRange',[147 149]} % gratings
%cellBoundary={'trialRange',[150]} % gratings
%cellBoundary={'trialRange',[151]} % gratings
%cellBoundary={'trialRange',[152]} % gratings
%cellBoundary={'trialRange',[153]} % gratings
%cellBoundary={'trialRange',[154]} % gratings
%cellBoundary={'trialRange',[155 158]} % gratings
%cellBoundary={'trialRange',[159]} % gratings
%cellBoundary={'trialRange',[160]} % gratings
%cellBoundary={'trialRange',[161]} % gratings
%cellBoundary={'trialRange',[162]} % gratings
%cellBoundary={'trialRange',[163]} % whiteNoise
%cellBoundary={'trialRange',[164 169]} % gratings
%cellBoundary={'trialRange',[170 175]} % gratings
%cellBoundary={'trialRange',[176 180]} % gratings
%cellBoundary={'trialRange',[181]} % gratings
%cellBoundary={'trialRange',[182]} % gratings
%cellBoundary={'trialRange',[183]} % gratings
%cellBoundary={'trialRange',[184]} % gratings
%cellBoundary={'trialRange',[185]} % whiteNoise
%cellBoundary={'trialRange',[186 190]} % gratings
%cellBoundary={'trialRange',[191]} % gratings
%cellBoundary={'trialRange',[192]} % gratings
%cellBoundary={'trialRange',[193]} % gratings
%cellBoundary={'trialRange',[194]} % gratings
%cellBoundary={'trialRange',[195]} % whiteNoise
%cellBoundary={'trialRange',[196]} % gratings
%cellBoundary={'trialRange',[197]} % gratings
%cellBoundary={'trialRange',[198]} % gratings
%cellBoundary={'trialRange',[199]} % gratings
%cellBoundary={'trialRange',[200 202]} % whiteNoise
%cellBoundary={'trialRange',[203]} % gratings
%cellBoundary={'trialRange',[204]} % gratings
%cellBoundary={'trialRange',[205]} % gratings
%cellBoundary={'trialRange',[206]} % gratings
%cellBoundary={'trialRange',[207]} % gratings
%cellBoundary={'trialRange',[208 211]} % whiteNoise
%cellBoundary={'trialRange',[212 224]} % whiteNoise
%cellBoundary={'trialRange',[225]} % gratings
%cellBoundary={'trialRange',[226 238]} % whiteNoise
%cellBoundary={'trialRange',[239 241]} % gratings
%cellBoundary={'trialRange',[242]} % whiteNoise
%cellBoundary={'trialRange',[243 257]} % whiteNoise
%cellBoundary={'trialRange',[258 308]} % whiteNoise
%cellBoundary={'trialRange',[309 318]} % whiteNoise
%cellBoundary={'trialRange',[319]} % whiteNoise
%cellBoundary={'trialRange',[320 333]} % whiteNoise
%cellBoundary={'trialRange',[334 337]} % whiteNoise
%cellBoundary={'trialRange',[338 340]} % gratings
%cellBoundary={'trialRange',[341]} % whiteNoise
%cellBoundary={'trialRange',[342 350]} % whiteNoise
%cellBoundary={'trialRange',[351]} % whiteNoise
%cellBoundary={'trialRange',[352 371]} % whiteNoise
%cellBoundary={'trialRange',[372]} % gratings
%cellBoundary={'trialRange',[373]} % whiteNoise
%cellBoundary={'trialRange',[374]} % whiteNoise
%cellBoundary={'trialRange',[375]} % whiteNoise
%cellBoundary={'trialRange',[376]} % gratings
%cellBoundary={'trialRange',[377]} % whiteNoise
analysisManagerByChunk(subjectID, path, cellBoundary, spikeDetectionParams, spikeSortingParams,timeRangePerTrialSecs,stimClassToAnalyze,overwriteAll,usePhotoDiodeSpikes,plottingParams)