%batch2pBehavior    JW 8/11/16

clear all

dbstop if error
pathname = '\\langevin\backup\twophoton\Newton\data\';
outpathname = '';
n=0;

%g62dd2ln
n=n+1;
files(n).subj = 'g62dd2ln'; 
files(n).expt = '032916';
files(n).dir = '032916 g62dd2ln GTS behavior\g62dd2ln';
files(n).compileData ='compiled_g62dd2ln_032916.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x4orientSessionV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sfSessionV2__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62dd2ln_001_003_eye';
files(n).passive3xStimrec = 'stim_obj_001_007';
files(n).passive2sfStimrec = 'stim_obj_001_008';
files(n).passive3xEyes = 'g62dd2ln_001_007_eye';
files(n).passive2sfEyes = 'g62dd2ln_001_008_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62dd2ln'; 
files(n).expt = '033016';
files(n).dir = '033016 g62dd2ln GTS behavior\g62dd2ln';
files(n).compileData ='compiled_g62dd2ln_033016.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x4orientSessionV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sfSessionV2__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62dd2ln_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_005';
files(n).passive2sfStimrec = 'stim_obj_001_006';
files(n).passive3xEyes = 'g62dd2ln_001_005_eye';
files(n).passive2sfEyes = 'g62dd2ln_001_006_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62dd2ln'; 
files(n).expt = '033116';
files(n).dir = '033116 g62dd2ln GTS behavior\g62dd2ln';
files(n).compileData ='compiled_g62dd2ln_033116.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x4orientSessionV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sfSessionV2__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62dd2ln_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_003';
files(n).passive3xEyes = 'g62dd2ln_001_004_eye';
files(n).passive2sfEyes = 'g62dd2ln_001_003_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected


n=n+1;
files(n).subj = 'g62dd2ln'; 
files(n).expt = '041116';
files(n).dir = '041116 g62dd2ln GTS behavior\g62dd2ln';
files(n).compileData ='compiled_g62dd2ln_041116.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x4orientSessionV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sfSessionV2__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62dd2ln_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_005';
files(n).passive2sfStimrec = 'stim_obj_001_006';
files(n).passive3xEyes = 'g62dd2ln_001_005_eye';
files(n).passive2sfEyes = 'g62dd2ln_001_006_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62dd2ln'; 
files(n).expt = '041216';
files(n).dir = '041216 g62dd2ln GTS behavior\g62dd2ln';
files(n).compileData ='compiled_g62dd2ln_041216.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x4orientSessionV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sfSessionV2__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62dd2ln_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_005';
files(n).passive3xEyes = 'g62dd2ln_001_004_eye';
files(n).passive2sfEyes = 'g62dd2ln_001_005_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected



%g62y3lt
n=n+1;
files(n).subj = 'g62y3lt'; 
files(n).expt = '050316';
files(n).dir = '050316 g62y3lt GTS behavior\g62y3lt';
files(n).compileData ='compiled_g62y3lt_050216.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x4orientSessionV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sfSessionV2__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62y3lt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_003';
files(n).passive2sfStimrec = 'stim_obj_001_004';
files(n).passive3xEyes = 'g62y3lt_001_003_eye';
files(n).passive2sfEyes = 'g62y3lt_001_004_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62y3lt'; 
files(n).expt = '050516';
files(n).dir = '050516 g62y3lt GTS behavior\g62y3lt';
files(n).compileData ='compiled_g62y3lt_050516.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x4orientSessionV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sfSessionV2__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62y3lt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_003';
files(n).passive2sfStimrec = 'stim_obj_001_004';
files(n).passive3xEyes = 'g62y3lt_001_003_eye';
files(n).passive2sfEyes = 'g62y3lt_001_004_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62y3lt'; 
files(n).expt = '050916';
files(n).dir = '050916 g62y3lt GTS behavior\g62y3lt';
files(n).compileData ='compiled_g62y3lt_050916.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x4orientSessionV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sfSessionV2__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62y3lt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_005';
files(n).passive3xEyes = 'g62y3lt_001_004_eye';
files(n).passive2sfEyes = 'g62y3lt_001_005_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62y3lt'; 
files(n).expt = '051616';
files(n).dir = '051616 g62y3lt GTS behavior\g62y3lt';
files(n).compileData ='compiled_g62y3lt_051616.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x4orientSessionV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sfSessionV2__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62y3lt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_003';
files(n).passive2sfStimrec = 'stim_obj_001_004';
files(n).passive3xEyes = 'g62y3lt_001_003_eye';
files(n).passive2sfEyes = 'g62y3lt_001_004_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected


%g62tx15lt
n=n+1;
files(n).subj = 'g62tx15lt'; 
files(n).expt = '060216';
files(n).dir = '060216 g62tx15lt GTS behavior\g62tx15lt';
files(n).compileData ='compiled_g62tx15lt_060216.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x4orientSessionV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sfSessionV2__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62tx15lt_001_001_eye';
files(n).passive3xStimrec = 'stim_obj_001_003';
files(n).passive2sfStimrec = 'stim_obj_001_002';
files(n).passive3xEyes = 'g62tx15lt_001_003_eye';
files(n).passive2sfEyes = 'g62tx15lt_001_002_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62tx15lt'; 
files(n).expt = '060616';
files(n).dir = '060616 g62tx15lt GTS behavior\g62tx15lt';
files(n).compileData ='compiled_g62tx15lt_060616.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x4orientSessionV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sfSessionV2__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62tx15lt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_005';
files(n).passive2sfStimrec = 'stim_obj_001_004';
files(n).passive3xEyes = 'g62tx15lt_001_005_eye';
files(n).passive2sfEyes = 'g62tx15lt_001_004_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62tx15lt'; 
files(n).expt = '060816';
files(n).dir = '060816 g62tx15lt GTS behavior\g62tx15lt';
files(n).compileData ='compiled_g62tx15lt_060816.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x4orientSessionV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sfSessionV2__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62tx15lt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_002';
files(n).passive2sfStimrec = 'stim_obj_001_001';
files(n).passive3xEyes = 'g62tx15lt_001_002_eye';
files(n).passive2sfEyes = 'g62tx15lt_001_001_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62tx15lt'; 
files(n).expt = '072916';
files(n).dir = '072916 g62tx15lt GTS behavior\g62tx15lt';
files(n).compileData ='compiled_g62tx15lt_072916.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sf8min__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62tx15lt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_003';
files(n).passive3xEyes = 'g62tx15lt_001_004_eye';
files(n).passive2sfEyes = 'g62tx15lt_001_003_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected



%g62bb10lt (gts)
n=n+1;
files(n).subj = 'g62bb10lt'; 
files(n).expt = '063016';
files(n).dir = '063016 g62bb10lt GTS behavior\g62bb10lt\';
files(n).compileData ='063016_g62bb10lt_compile.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';
files(n).passive2sfPts = 'passiveBehav2sf8minSessionV2__allfiles_PTS_dF';
files(n).behavEyes = 'g62bb10lt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_003';
files(n).passive3xEyes = 'g62bb10lt_001_004_eye';
files(n).passive2sfEyes = 'g62bb10lt_001_003_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected


n=n+1;
files(n).subj = 'g62bb10lt'; 
files(n).expt = '070716';
files(n).dir = '070716 g62bb10lt GTS behavior\g62bb10lt\';
files(n).compileData ='compiled_g62bb10lt_070716.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';
files(n).passive2sfPts = 'passiveBehav2sf8minSessionV2__allfiles_PTS_dF';
files(n).behavEyes = 'g62bb10lt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_003';
files(n).passive3xEyes = 'g62bb10lt_001_004_eye';
files(n).passive2sfEyes = 'g62bb10lt_001_003_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected


n=n+1;
files(n).subj = 'g62bb10lt'; 
files(n).expt = '071316';
files(n).dir = '071316 g62bb10lt GTS behavior\g62bb10lt\';
files(n).compileData ='compiled_g62bb10lt_071316.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';
files(n).passive2sfPts = 'passiveBehav2sf8minSessionV2__allfiles_PTS_dF';
files(n).behavEyes = 'g62bb10lt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_005';
files(n).passive3xEyes = 'g62bb10lt_001_004_eye';
files(n).passive2sfEyes = 'g62bb10lt_001_005_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62bb10lt'; 
files(n).expt = '071716';
files(n).dir = '071716 g62bb10lt GTS behavior\g62bb10lt\';
files(n).compileData ='compiled_g62bb10lt_071716.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';
files(n).passive2sfPts = 'passiveBehav2sf8minSessionV2__allfiles_PTS_dF';
files(n).behavEyes = 'g62bb10lt_001_002_eye';
files(n).passive3xStimrec = 'stim_obj_001_007';
files(n).passive2sfStimrec = 'stim_obj_001_006';
files(n).passive3xEyes = 'g62bb10lt_001_007_eye';
files(n).passive2sfEyes = 'g62bb10lt_001_006_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62bb10lt'; 
files(n).expt = '072616';
files(n).dir = '072616 g62bb10lt GTS behavior\g62bb10lt\';
files(n).compileData ='compiled_g62bb10lt_072616.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';
files(n).passive2sfPts = 'passiveBehav2sf8minSessionV2__allfiles_PTS_dF';
files(n).behavEyes = 'g62bb10lt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_003';
files(n).passive3xEyes = 'g62bb10lt_001_004_eye';
files(n).passive2sfEyes = 'g62bb10lt_001_003_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62bb10lt'; 
files(n).expt = '072716';
files(n).dir = '072716 g62bb10lt GTS behavior\g62bb10lt\';
files(n).compileData ='compiled_g62bb10lt_072716.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';
files(n).passive2sfPts = 'passiveBehav2sf8minSessionV2__allfiles_PTS_dF';
files(n).behavEyes = 'g62bb10lt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_003';
files(n).passive3xEyes = 'g62bb10lt_001_004_eye';
files(n).passive2sfEyes = 'g62bb10lt_001_003_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62bb10lt'; 
files(n).expt = '072816';
files(n).dir = '072816 g62bb10lt GTS behavior\g62bb10lt\';
files(n).compileData ='compiled_g62bb10lt_072816.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';
files(n).passive2sfPts = 'passiveBehav2sf8minSessionV2__allfiles_PTS_dF';
files(n).behavEyes = 'g62bb10lt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_003';
files(n).passive3xEyes = 'g62bb10lt_001_004_eye';
files(n).passive2sfEyes = 'g62bb10lt_001_003_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected

%g62gg5rt (GTS)

n=n+1;
files(n).subj = 'g62gg5rt'; 
files(n).expt = '080316';
files(n).dir = '080316 g62gg5rt GTS behavior\g62gg5rt';
files(n).compileData ='compiled_g62gg5rt_080316.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sf8min__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62gg5rt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_003';
files(n).passive3xEyes = 'g62gg5rt_001_004_eye';
files(n).passive2sfEyes = 'g62gg5rt_001_003_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62gg5rt'; 
files(n).expt = '080916';
files(n).dir = '080916 g62gg5rt GTS behavior\g62gg5rt';
files(n).compileData ='compiled_g62gg5rt_080916.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sf8min__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62gg5rt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_003';
files(n).passive3xEyes = 'g62gg5rt_001_004_eye';
files(n).passive2sfEyes = 'g62gg5rt_001_003_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62gg5rt'; 
files(n).expt = '081016';
files(n).dir = '081016 g62gg5rt GTS behavior\g62gg5rt';
files(n).compileData ='compiled_g62gg5rt_081016.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sf8min__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62gg5rt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_003';
files(n).passive3xEyes = 'g62gg5rt_001_004_eye';
files(n).passive2sfEyes = 'g62gg5rt_001_003_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected


n=n+1;
files(n).subj = 'g62gg5rt'; 
files(n).expt = '081216';
files(n).dir = '081216 g62gg5rt GTS behavior\g62gg5rt';
files(n).compileData ='compiled_g62gg5rt_081216.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sf8min__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62gg5rt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_003';
files(n).passive3xEyes = 'g62gg5rt_001_004_eye';
files(n).passive2sfEyes = 'g62gg5rt_001_003_eye';
files(n).task = 'GTS';
files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected




%%g62ff8rt (naive)  %first naive session 071916  %%% started behav 070116
n=n+1;
files(n).subj = 'g62ff8rt'; 
files(n).expt = '072116';
files(n).dir = '072116 g62ff8rt Naive behavior\g62ff8rt';
files(n).compileData ='compiled_g62ff8rt_072116.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sf8min__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62ff8rt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_003';
files(n).passive3xEyes = 'g62ff8rt_001_004_eye';
files(n).passive2sfEyes = 'g62ff8rt_001_003_eye';
files(n).task = 'Naive';
files(n).learningDay = [3];   %%% can probably ignore for GTS, more important for naive
files(n).totalDays = 20;
files(n).totalSinceGratings = 2;
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62ff8rt'; 
files(n).expt = '072216';
files(n).dir = '072216 g62ff8rt Naive behavior\g62ff8rt';
files(n).compileData ='compiled_g62ff8rt_072216.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sf8min__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62ff8rt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_003';
files(n).passive3xEyes = 'g62ff8rt_001_004_eye';
files(n).passive2sfEyes = 'g62ff8rt_001_003_eye';
files(n).task = 'Naive';
files(n).learningDay = [4];   %%% can probably ignore for GTS, more important for naive
files(n).totalSinceGratings = 3;
files(n).totalDays = 21;
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62ff8rt'; 
files(n).expt = '072716';
files(n).dir = '072716 g62ff8rt Naive behavior\g62ff8rt';
files(n).compileData ='compiled_g62ff8rt_072716.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sf8min__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62ff8rt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_003';
files(n).passive3xEyes = 'g62ff8rt_001_004_eye';
files(n).passive2sfEyes = 'g62ff8rt_001_003_eye';
files(n).task = 'Naive';
files(n).learningDay = [6];   %%% can probably ignore for GTS, more important for naive
files(n).totalSinceGratings = 8;
files(n).totalDays = 26;
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62ff8rt'; 
files(n).expt = '072816';
files(n).dir = '072816 g62ff8rt Naive behavior\g62ff8rt';
files(n).compileData ='072816_g62ff8rt_compiled.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sf8min__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62ff8rt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_003';
files(n).passive3xEyes = 'g62ff8rt_001_004_eye';
files(n).passive2sfEyes = 'g62ff8rt_001_003_eye';
files(n).task = 'Naive';
files(n).learningDay = [7];   %%% can probably ignore for GTS, more important for naive
files(n).totalSinceGratings = 9;
files(n).totalDays = 27;
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected


n=n+1;
files(n).subj = 'g62ff8rt'; 
files(n).expt = '082416';
files(n).dir = '082416 g62ff8rt Naive behavior\g62ff8rt';
files(n).compileData ='compiled_g62ff8rt_082416';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sf8min__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = '';% no eye data for this session
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_003';
files(n).passive3xEyes = 'g62ff8rt_001_004_eye';
files(n).passive2sfEyes = 'g62ff8rt_001_003_eye';
files(n).task = 'Naive';
files(n).learningDay = [8];   %%% can probably ignore for GTS, more important for naive
files(n).totalSinceGratings = 35;
files(n).totalDays = 53;
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected


%g62bb12lt (naive) %first naive session 060216 %%% started behav 051216
n=n+1;
files(n).subj = 'g62bb12lt'; 
files(n).expt = '060716';
files(n).dir = '060716 g62bb12lt Naive behavior\g62bb12lt';
files(n).compileData ='compiled_g62bb12lt_060716.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sf8min__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62bb12lt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_003';
files(n).passive3xEyes = 'g62bb12lt_001_004_eye';
files(n).passive2sfEyes = 'g62bb12lt_001_003_eye';
files(n).task = 'Naive';
files(n).learningDay = [2];   %%% can probably ignore for GTS, more important for naive
files(n).totalSinceGratings = 5;
files(n).totalDays = 26;
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62bb12lt'; 
files(n).expt = '060816';
files(n).dir = '060816 g62bb12lt Naive behavior\g62bb12lt';
files(n).compileData ='compiled_g62bb12lt_060816.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sf8min__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62bb12lt_001_001_eye';
files(n).passive3xStimrec = 'stim_obj_001_003';
files(n).passive2sfStimrec = 'stim_obj_001_002';
files(n).passive3xEyes = 'g62bb12lt_001_003_eye';
files(n).passive2sfEyes = 'g62bb12lt_001_002_eye';
files(n).task = 'Naive';
files(n).learningDay = [3];   %%% can probably ignore for GTS, more important for naive
files(n).totalSinceGratings = 6;
files(n).totalDays = 27;
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62bb12lt'; 
files(n).expt = '071916';
files(n).dir = '071916 g62bb12lt Naive behavior\g62bb12lt';
files(n).compileData ='compiled_g62bb12lt_071916.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sf8min__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62bb12lt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_003';
files(n).passive3xEyes = 'g62bb12lt_001_004_eye';
files(n).passive2sfEyes = 'g62bb12lt_001_003_eye';
files(n).task = 'Naive';
files(n).learningDay = [5];   %%% can probably ignore for GTS, more important for naive
files(n).totalSinceGratings = 47;
files(n).totalDays = 68;
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62bb12lt'; 
files(n).expt = '072116';
files(n).dir = '072116 g62bb12lt Naive behavior\g62bb12lt';
files(n).compileData ='compiled_g62bb12lt_072116.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sf8min__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62bb12lt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_003';
files(n).passive3xEyes = 'g62bb12lt_001_004_eye';
files(n).passive2sfEyes = 'g62bb12lt_001_003_eye';
files(n).task = 'Naive';
files(n).learningDay = [7];   %%% can probably ignore for GTS, more important for naive
files(n).totalSinceGratings = 49;
files(n).totalDays = 70;
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = 250;  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62bb12lt'; 
files(n).expt = '072216';
files(n).dir = '072216 g62bb12lt Naive behavior\g62bb12lt';
files(n).compileData ='072216_g62bb12lt_compiled.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sf8min__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62bb12lt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_003';
files(n).passive3xEyes = 'g62bb12lt_001_004_eye';
files(n).passive2sfEyes = 'g62bb12lt_001_003_eye';
files(n).task = 'Naive';
files(n).learningDay = [8];   %%% can probably ignore for GTS, more important for naive
files(n).totalSinceGratings = 50;
files(n).totalDays = 71;
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = 200;  %%% optional - we could use this to adjust # of cells selected

%g62kk7lt (naive) %first naive session 060216 %%% started behav 080216

n=n+1;
files(n).subj = 'g62kk7lt'; 
files(n).expt = '081616';
files(n).dir = '081616 g62kk7lt Naive behavior\g62kk7lt';
files(n).compileData ='compiled_g62kk7lt_081616.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sf8min__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62kk7lt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_005';
files(n).passive2sfStimrec = 'stim_obj_001_004';
files(n).passive3xEyes = 'g62kk7lt_001_005_eye';
files(n).passive2sfEyes = 'g62kk7lt_001_004_eye';
files(n).task = 'Naive';
files(n).learningDay = [1];   %%% can probably ignore for GTS, more important for naive
files(n).totalSinceGratings = 1;
files(n).totalDays = 14;
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected


n=n+1;
files(n).subj = 'g62kk7lt'; 
files(n).expt = '081816';
files(n).dir = '081816 g62kk7lt Naive behavior\g62kk7lt';
files(n).compileData ='compiled_g62kk7lt_081816.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sf8min__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62kk7lt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_003';
files(n).passive3xEyes = 'g62kk7lt_001_004_eye';
files(n).passive2sfEyes = 'g62kk7lt_001_003_eye';
files(n).task = 'Naive';
files(n).learningDay = [3];   %%% can probably ignore for GTS, more important for naive
files(n).totalSinceGratings = 3;
files(n).totalDays = 16;
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = 100;  %%% optional - we could use this to adjust # of cells selected

n=n+1;
files(n).subj = 'g62kk7lt'; 
files(n).expt = '081916';
files(n).dir = '081916 g62kk7lt Naive behavior\g62kk7lt';
files(n).compileData ='compiled_g62kk7lt_081916.mat';  
files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
files(n).topoX = 'topoXsessionV2';
files(n).topoY = 'topoYsessionV2';
files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
files(n).passive2sfPts = 'passiveBehav2sf8min__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
files(n).behavEyes = 'g62kk7lt_001_000_eye';
files(n).passive3xStimrec = 'stim_obj_001_004';
files(n).passive2sfStimrec = 'stim_obj_001_003';
files(n).passive3xEyes = 'g62kk7lt_001_004_eye';
files(n).passive2sfEyes = 'g62kk7lt_001_003_eye';
files(n).task = 'Naive';
files(n).learningDay = [4];   %%% can probably ignore for GTS, more important for naive
files(n).totalSinceGratings = 4;
files(n).totalDays = 17;
files(n).label = 'camk2 gc6';
files(n).notes = 'good imaging session';
files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected


% n=n+1;
% files(n).subj = ''; 
% files(n).expt = '';
% files(n).dir = '';
% files(n).compileData ='';  
% files(n).topoXpts = 'topoXsessionV2__allfiles_PTS_dF';
% files(n).topoYpts = 'topoYsessionV2__allfiles_PTS_dF';
% files(n).topoX = 'topoXsessionV2';
% files(n).topoY = 'topoYsessionV2';
% files(n).behavPts = 'behavSessionV2__allfiles_PTS_dF.mat';
% files(n).passive3xPts = 'passiveBehav3x8minV2__allfiles_PTS_dF';%or passiveBehav3x4orient__allfiles_PTS_dF
% files(n).passive2sfPts = 'passiveBehav2sf8min__allfiles_PTS_dF'; %or passiveBehav2sfSessionV2__allfiles_PTS_dF
% files(n).behavEyes = '';
% files(n).passive3xStimrec = '';
% files(n).passive2sfStimrec = '';
% files(n).passive3xEyes = '';
% files(n).passive2sfEyes = '';
% files(n).task = '';
% files(n).learningDay = [];   %%% can probably ignore for GTS, more important for naive
% files(n).totalSinceGratings = ;
% files(n).totalDays = ;
% files(n).label = 'camk2 gc6';
% files(n).notes = 'good imaging session';
% files(n).ncells = [];  %%% optional - we could use this to adjust # of cells selected
