function [img, framerate] = readAlign2p_sbx(fn, align,showImg, chan)
%%% reads in scanbox data, using sbx read
%%%
%%% inputs:
%%% fn = filename
%%% align = perform alignement
%%% showImg = show images generated by this function? (to avoid figure proliferation)
%%% chan = which pmt chan to use (default = 1, if this variable is not passed)
%%%
%%% outputs:
%%% img = raw data frames
%%% framerate = acquisition framerate

d =sbxread(fn,1,1);            % read one frame to read the header of the image sequence
global info;                % this contains the information about the structure of the image

%%%default channel to read is 1
if ~exist('chan','var') 
    chan =1;
end

if chan==2 & size(d,1)==1  %%% asking for channel 2, but there's only one in data
    display('you asked for channel 2, but theres only 1')
    img=NaN; framerate=NaN;
    return
end

if (exist([fn '.align'])==0 & align)
    
    [m,T] = sbxalignx(fn,0:info.max_idx-1);   %
    save([fn '.align'],'m','T');
    display(sprintf('Done %s: Aligned %d images in %d min',fn,info.max_idx,round(toc/60)))
end

if isempty(info.aligned) %%% sometimes occurs if previously aligned, but not loaded into info
    load([fn '.align'],'-mat','m','T');
    info.aligned.m=m; info.aligned.T=T;
end

sbxread(fn,1,1);            % read one frame to read the header of the image sequence


if align
    figure
    plot(info.aligned.T);
    
    m=double(info.aligned.m);
    upper = prctile(m(:),95)*1.2;
    lower = min(m(:));
    if showImg
        figure
        imagesc(m,[lower upper]); colormap gray; title('sbx aligned mean'); axis equal
    end
    drawnow
end



img = zeros(info.sz(1),info.sz(2),info.max_idx,'uint16');
for i = 1:info.max_idx;
    im = sbxread(fn,i-1,1);
    if align
        img(:,:,i)  = circshift(squeeze(im(chan,:,:)),info.aligned.T(i,:));
    else
        img(:,:,i)=im;
    end
end

m = mean(img,3);
upper = prctile(m(:),95)*1.2;
lower = min(m(:));
if showImg
    figure
    imagesc(m,[lower upper]); colormap gray; title('readAlign mean'); axis equal
    drawnow
end

framerate = info.resfreq/info.config.lines;

