function p=getPositionInBregmaCoordinates(eventdata,which)
% eventdata- as generated by physiologySever event logger
% which - a logical (or index) into which events

raw_position=vertcat(eventdata(which).position);
surgeryA=vertcat(eventdata(which).surgeryAnchor);
surgeryB=vertcat(eventdata(which).surgeryBregma);
A=vertcat(eventdata(which).currentAnchor);

%get translation from surgery
translation=surgeryB-surgeryA;  % distance to surgery anchor from bregma
translation(:,1)=-abs(translation(:,1)); %enforce anchor is posterior to bregma
translation(:,2)=-abs(translation(:,2)); %enforce anchor is to the left of bregma

% calculate current position
current_offset=(raw_position-A); % distance to current anchor from current position
%convert from rig1's inverted position (posterior positive; left postive) to matlabs axis (anterior positive; right positive)
current_offset(:,1)=-current_offset(:,1); % flip AP
current_offset(:,2)=-current_offset(:,2); % flipML

p=current_offset+translation;  % in rig one larger number are posterior