function d=display(s)
    d=['coherentDots (n target, m distractor gabors, randomized phase, equal spatial frequency, p>=n+m horiz positions)\n'...
        '\t\t\tpixPerCycs:\t[' num2str(1) ... 
        ']\n\t\t\ttarget orientations:\t[' num2str(1) ...
        ']\n\t\t\tdistractor orientations:\t[' num2str(1) ...
        ']\n\t\t\tmean:\t' num2str(1) ...
        '\n\t\t\tradius:\t' num2str(1) ...
        '\n\t\t\tcontrast:\t' num2str(1) ...
        '\n\t\t\tthresh:\t' num2str(1) ...
        '\n\t\t\tpct from top:\t' num2str(1)];
    d=sprintf(d);
    
    %%% TODO:  change this
    %%% num2str(s.pixPerCycs)