function out=getEyeDataVarNames(t)

out={'timeEyelink',...  %renamed from 'time'
    'type',...
    'flags',...
    ...%                 'px_left',... % removed eye side naming
    ...%                 'px_right',...
    ...%                 'py_left',...
    ...%                 'py_right',...
    ...%                 'hx_left',...
    ...%                 'hx_right',...
    ...%                 'hy_left',...
    ...%                 'hy_right',...
    ...%                 'pa_left',...
    ...%                 'pa_right',...
    ...%                 'gx_left',...
    ...%                 'gx_right',...
    ...%                 'gy_left',...
    ...%                 'gy_right',...
    'px',...
    'py',...
    'hx',...
    'hy',...
    'pa',...
    'gx',...
    'gy',...
    ...
    'rx',...
    'ry',...
    'status',...
    'input',...
    'buttons',...
    'htype',...
    'hdata1',...
    'hdata2',...
    'hdata3',...
    'hdata4',...
    'hdata5',...
    'hdata6',...
    'hdata7',...
    'hdata8',...
    'raw_pupil_x',...
    'raw_pupil_y',...
    'raw_cr_x',...
    'raw_cr_y',...
    'pupil_area',...
    'cr_area',...
    'pupil_dimension_x',...
    'pupil_dimension_y',...
    'cr_dimension_x',...
    'cr_dimension_y',...
    'window_position_x',...
    'window_position_y',...
    'pupil_cr_x',...
    'pupil_cr_y',...
    'cr_area2',...
    'raw_cr2_x',...
    'raw_cr2_y'...
    'timeCPU',... % added on afterwards
    'date'};  % added on afterwards
