function out=getAnalysisFields(s)
%list of fields inside stimDetails, that are desired for analysis, and
%should be in complied records

out={'correctionTrial','.stimDetails.correctionTrial','int8';...
    'correctResponseIsLeft','.stimDetails.correctResponseIsLeft','int8';...
    'targetContrast','.stimDetails.targetContrast','double';...
    'targetOrientation','.stimDetails.targetOrientation','double';...
    'flankerContrast','.stimDetails.flankerContrast','double';...
    'flankerOrientation','.stimDetails.flankerOrientation(1)','double';... %need to deal with when there is more than 1 flanker!
    'deviation','.stimDetails.deviation','double';...
    'devPix','.stimDetails.devPix','double';...
    'targetPhase','.stimDetails.targetPhase','double';...
    'flankerPhase','.stimDetails.flankerPhase','double';...
    'currentShapedValue','.stimDetails.currentShapedValue','double';...
    'pixPerCycs','.stimDetails.pixPerCycs','double';...
    'redLUT','.stimDetails.LUT(end,1)','double';...
    'stdGaussMask','.stimDetails.stdGaussMask','double';...
    'maxCorrectForceSwitch','.stimDetails.maxCorrectForceSwitch','double'}