function d=display(r)
    d=[sprintf('\n\t\t\trewardNthCorrect:\t\t\t%s',num2str(r.rewardNthCorrect)) ...
       sprintf('\n\t\t\tmsPenalty:\t\t\t\t\t%d',r.msPenalty) ...
       sprintf('\n\t\t\tscalar:\t\t\t\t\t %3.0g',r.scalar) ...
       ];
   
   %add on the superclass 
    d=[d sprintf('\n\t\treinforcementManager:\t') display(r.reinforcementManager)];